<?php

/**
 * @file
 * Preprocess hooks and other theme functions for the OpenDrupal Agency theme.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function opendrupal_agency_page_attachments_alter(array &$attachments) {
}

/**
 * Implements hook_js_alter().
 */
function opendrupal_agency_js_alter(&$javascripts) {
}

/**
 * Implements hook_preprocess_html().
 */
function opendrupal_agency_preprocess_html(&$variables) {
}